"""Unified network services migration

Revision ID: 08c8c78dbeaf
Revises: 4931a094c6d8
Create Date: 2020-03-30 11:00:37.329723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '08c8c78dbeaf'
down_revision = '4931a094c6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('vim_image', sa.String(length=256), nullable=True),
    sa.Column('vim_location', sa.String(length=64), nullable=True),
    sa.Column('vim_id', sa.String(length=256), nullable=True),
    sa.Column('nsd_file', sa.String(length=256), nullable=True),
    sa.Column('nsd_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnfd_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('vnfd_file', sa.String(length=256), nullable=True),
    sa.Column('vnfd_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['network_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('VNF')
    op.drop_table('NS')
    #op.drop_constraint(None, 'experiments_ns', type_='foreignkey')
    #op.create_foreign_key(None, 'experiments_ns', 'network_service', ['ns_id'], ['id'])
    # ### end Alembic commands ###

    # ALTER commands for sqlite
    op.get_bind().execute(text("""
        create table experiments_ns_dg_tmp (
            experiment_id INTEGER constraint experiments_ns_experiment_id_fk references experiment(id),
            ns_id INTEGER constraint experiments_ns_network_service_id_fk references network_service(id)
            );
    """))

    op.get_bind().execute(text("""
        insert into experiments_ns_dg_tmp(experiment_id, ns_id) select experiment_id, ns_id from experiments_ns;
    """))

    op.get_bind().execute(text("""
        drop table experiments_ns;
    """))

    op.get_bind().execute(text("""
        alter table experiments_ns_dg_tmp rename to experiments_ns;
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiments_ns', type_='foreignkey')
    op.create_foreign_key(None, 'experiments_ns', 'NS', ['ns_id'], ['id'])
    op.create_table('NS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('NSD', sa.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VNF',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('VNFD', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vnfd_package')
    op.drop_table('network_service')
    # ### end Alembic commands ###
