"""Add reservation time

Revision ID: 38a1ecff2c63
Revises: 55e421f8c2c0
Create Date: 2020-04-14 13:39:13.402400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a1ecff2c63'
down_revision = '55e421f8c2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('reservation_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'reservation_time')
    # ### end Alembic commands ###
