"""Add 'finished' column to OnboardStatus

Revision ID: 71a4884887d8
Revises: afafec9f8416
Create Date: 2020-03-20 12:10:09.051707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a4884887d8'
down_revision = 'afafec9f8416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboard_status', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboard_status', 'finished')
    # ### end Alembic commands ###
