"""Add new network service tables

Revision ID: 8e4424ad44fa
Revises: 4931a094c6d8
Create Date: 2020-03-16 13:03:42.401508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4424ad44fa'
down_revision = '4931a094c6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('vim_image', sa.String(length=256), nullable=True),
    sa.Column('vim_location', sa.String(length=64), nullable=True),
    sa.Column('nsd_file', sa.String(length=256), nullable=True),
    sa.Column('nsd_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnfd_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('vnfd_file', sa.String(length=256), nullable=True),
    sa.Column('vnfd_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['network_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vnfd_package')
    op.drop_table('network_service')
    # ### end Alembic commands ###
