"""Add vim_id

Revision ID: c122d66179b6
Revises: 27a57debb9d9
Create Date: 2020-03-18 13:42:58.468923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c122d66179b6'
down_revision = '27a57debb9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_service', sa.Column('vim_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_service', 'vim_id')
    # ### end Alembic commands ###
